# 넘파이 시작하기

## 넘파이 배열

In [1]:
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

In [2]:
[[i + 1 for i in row] for row in matrix]

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

In [3]:
# 먼저 넘파이를 임포트합니다
import numpy as np

In [4]:
# 리스트로 배열을 만들면 1차원 배열이 만들어집니다
array1 = np.array([10, 100, 1000.])

In [5]:
# 중첩된 리스트로 배열을 만들면 2차원 배열이 만들어집니다
array2 = np.array([[1., 2., 3.],
                   [4., 5., 6.]])

In [6]:
array1.dtype

dtype('float64')

In [7]:
float(array1[0])

10.0

## 벡터화와 브로드캐스팅

In [8]:
array2 + 1

array([[2., 3., 4.],
       [5., 6., 7.]])

In [9]:
array2 * array2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [10]:
array2 * array1

array([[  10.,  200., 3000.],
       [  40.,  500., 6000.]])

In [11]:
array2 @ array2.T # array2.T 는 array2.transpose()를 뜻합니다

array([[14., 32.],
       [32., 77.]])

## 범용 함수

In [13]:
import math
np.array([[math.sqrt(i) for i in row] for row in array2])

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [14]:
np.sqrt(array2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [15]:
array2.sum(axis=0) # 1차원 배열을 반환합니다.

array([5., 7., 9.])

In [16]:
array2.sum()

21.0

# 배열 생성과 조작

## 배열 요소 접근과 설정

In [17]:
array1[2] # 스칼라 값을 반환합니다

1000.0

In [18]:
array2[0, 0] # 스칼라 값을 반환합니다

1.0

In [19]:
array2[:, 1:] # 2차원 배열을 반환합니다

array([[2., 3.],
       [5., 6.]])

In [20]:
array2[:, 1] # 1차원 배열을 반환합니다.

array([2., 5.])

In [24]:
array2[1, :2] # 1차원 배열을 반환합니다.

array([4., 5.])

## 유용한 배열 생성자

In [25]:
np.arange(2 * 5.).reshape(2, 5) # 2행 5열

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [26]:
np.random.randn(2, 3) # 2행 3열

array([[ 1.28634892,  0.34209919, -0.35269472],
       [ 0.26028513,  0.14322777,  0.25929179]])

## 뷰와 사본

In [27]:
array2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
subset = array2[:, :2]

In [29]:
subset[0, 0] = 1000

In [30]:
subset

array([[1000.,    2.],
       [   4.,    5.]])

In [31]:
array2

array([[1000.,    2.,    3.],
       [   4.,    5.,    6.]])