# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [1]:
import numpy as np
np.__version__

'1.19.5'



---



## 배열 생성

### 리스트로 배열 만들기


In [7]:
a1 = np.array([1, 2, 3,4,5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[2], a1[3], a1[4])
a1[0] = 4
a1[1] = 5
a1[2] =6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 3 4 5
[4 5 6 4 5]


In [13]:
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a2)
print(a2.shape)
print(a2[0,0], a2[1,1], a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [20]:
a3 = np.array([ [[1,2,3],[4,5,6], [7,8,9]],
                [[1,2,3],[4,5,6], [7,8,9]],
                [[1,2,3],[4,5,6], [7,8,9]]])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `ones()`: 모든 요소를 1로 초기화

In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [25]:
np.full((3,3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [27]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [28]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [30]:
print(a1)
np.zeros_like(a1)

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [32]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [34]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [35]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [37]:
np.logspace(0.1, 1,20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [39]:
np.random.random((3,3))

array([[0.85892043, 0.00811291, 0.88873771],
       [0.76654654, 0.68427505, 0.03222744],
       [0.22770778, 0.65014736, 0.25935528]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [40]:
np.random.randint(0,10,(3,3))

array([[9, 2, 4],
       [8, 7, 4],
       [7, 6, 9]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [41]:
np.random.normal(0, 1, (3,3))

array([[ 0.59613996,  1.08949131, -1.66188878],
       [ 1.01838729,  0.01012766,  1.56115829],
       [-0.34599469,  1.03712363,  0.23218081]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [43]:
np.random.rand(3,3)

array([[0.43376626, 0.84827617, 0.88071053],
       [0.72557443, 0.3812481 , 0.85328479],
       [0.60865345, 0.22768578, 0.76626055]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [44]:
np.random.randn(3,3)

array([[ 1.3070386 , -0.35497394, -1.16083381],
       [-1.44974093,  0.09096081, -0.18562313],
       [ 0.25650495,  1.97947142, -1.5300672 ]])

### 표준 데이터 타입

In [45]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [47]:
np.full((3,3), 1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성


In [48]:
date = np.array('2020-01-01',dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [50]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [51]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [52]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')



---



## 배열 조회

### 배열 속성 정보

In [54]:
def array_info(array):
  print(array)
  print("ndim:", array.ndim)
  print("shape:", array.shape)
  print("dtype:", array.dtype)
  print("size:", array.size)
  print("itemsize",array.itemsize)
  print("nbytes:", array.nbytes)
  print("strides:", array.strides)

In [55]:
array_info(a1)

[4 5 6 4 5]
ndim: 1
shape: (5,)
dtype: int64
size: 5
itemsize 8
nbytes: 40
strides: (8,)


In [56]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int64
size: 9
itemsize 8
nbytes: 72
strides: (24, 8)


In [57]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int64
size: 27
itemsize 8
nbytes: 216
strides: (72, 24, 8)


### 인덱싱(Indexing)

In [59]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 5 6 4 5]
4
6
5
4


In [60]:
print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[1,1])
print(a2[2,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [61]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[2,2,2])
print(a3[2,-1,-1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [62]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 6 4 5]
[4 5]
[4 5 6 4 5]
[4]
[4 6 5]
[5 4 6 5 4]


In [64]:
print(a2)
print(a2[1])
print(a2[1,:])
print(a2[:2,:2])
print(a2[1:,::-1])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [68]:
print(a1)
bi = [False,True, True, False, True]
print(a1[bi])
bi = [True, False, True, True, False]
print(a1[bi])

[4 5 6 4 5]
[5 6 5]
[4 6 4]


In [71]:
print(a2)
bi = np.random.randint(0, 2, (3,3), dtype = bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [ True False  True]
 [ True  True  True]]
[4 6 7 8 9]


### 팬시 인덱싱(Fancy Indedxing)

In [74]:
print(a1)
print(a1[0], a1[2])
ind= [0,2]
print(a1[ind])
ind = np.array([[0,1],
                [2,0]])
print(a1[ind])

[4 5 6 4 5]
4 6
[4 6]
[[4 5]
 [6 4]]


In [76]:
print(a2)
row = np.array([0,1])
col = np.array([1,2])
print(a2[row, col])
print(a2[row, :])
print(a2[:,col])
print(a2[row, 1])
print(a2[2, col])
print(a2[row,1:])
print(a2[1:,col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 6]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]
[2 5]
[8 9]
[[2 3]
 [5 6]]
[[5 6]
 [8 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [81]:
print(a1)
b1 = np.insert(a1,0,10)
print(b1)
c1= np.insert(a1,2,10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[ 4  5 10  6  4  5]


In [84]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0)
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [88]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1,3,4])
a1[i] = 0
print(a1)
a1[1] += 4
print(a1)

[9 0 3 0 0]
[1 2 3 0 0]
[9 2 3 0 0]
[9 0 3 0 0]
[9 4 3 0 0]


In [92]:
print(a2)
a2[0,0] = 1
a2[1,1] = 2
a2[2,2] =3
a2[0]= 1
print(a2)
a2[1:,2] = 9
print(a2)
row=np.array([0,1])
col = np.array([1,2])
a2[row, col] = 0
print(a2)

[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 1 1]
 [4 2 9]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [95]:
print(a1)
b = np.delete(a1, 1)
print(b1)
print(a1)

[9 4 3 0 0]
[10  4  5  6  4  5]
[9 4 3 0 0]


In [97]:
print(a2)
b2 = np.delete(a2, 1 ,axis=0)
print(b2)
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [102]:
print(a2)
print(a2[:2,:2])
a2_sub = a2[:2,:2]
print(a2_sub)
a2_sub[:,1] = 0
print(a2_sub)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [105]:
print(a2)
a2_sub_copy = a2[:2,:2].copy()
print(a2_sub_copy)
a2_sub_copy[:,1] = 1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [106]:
print(a2)
print(a2.T)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [107]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [108]:
print(a2)
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [109]:
print(a3)
print(a3.swapaxes(0,1))
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [111]:
n1 = np.arange(1,10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [112]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [113]:
n2 = np.random.randint(0,10, (2,5))
print(n2)
n2.resize((5,2))
print(n2)

[[9 6 4 5 3]
 [6 4 9 5 0]]
[[9 6]
 [4 5]
 [3 6]
 [4 9]
 [5 0]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [118]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [119]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [120]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [121]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [123]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])

array([1, 3, 5, 2, 4, 6])

In [124]:
c1 = np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [125]:
a2 = np.array([[1,2,3],
               [4,5,6]])
np.concatenate([a2,b2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [127]:
a2 = np.array([[1,2,3],
               [4,5,6]])
np.concatenate([a2,a2],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [128]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [129]:
np.hstack([a2,a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [130]:
np.dstack([a2,a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* `stack()`: 새로운 차원으로 연결

In [131]:
np.stack([a2,a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

* `split()`: 배열 분할

In [134]:
a1 = np.arange(0,10)
print(a1)
b1, c1 = np.split(a1, [5])
print(b1,c1)
b1, c1, d1, e1, f1 = np.split(a1, [2,4,6,8])
print(b1,c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [135]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.vsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [136]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.hsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [137]:
a3 = np.arange(1,28).reshape(3,3,3)
print(a3)
b3,c3 = np.vsplit(a3,[2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[[[19 20 21]
  [22 23 24]
  [25 26 27]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [138]:
a1 = np.array([1,2,3])
print(a1)
print(a1 + 5)

[1 2 3]
[6 7 8]


In [140]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(a1 + a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [141]:
b2 = np.array([1,2,3]).reshape(3,1)
print(b2)
print(a1 + b2)

[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

In [148]:
a1 = np.arange(1, 10)
print(a1)
print(a1 + 1)
print(np.add(a1,10))
print(a1 - 2)
print(np.subtract(a2,10))
print(-a1)
print(np.negative(a1))
print(a2 *2)
print(np.multiply(a1,2))
print(a1/2)
print(np.divide(a2,2))
print(a1//2)
print(np.floor_divide(a1,2))
print(a1 ** 2)
print(np.power(a1,2))
print(a1 %2)
print(np.mod(a1,2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [150]:
a1 = np.arange(1,10)
print(a1)
b1 = np.random.randint(1,10,size=9)
print(b1)
print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(a1 // b1)
print(a1**b1)
print(a1%b1)

[1 2 3 4 5 6 7 8 9]
[8 9 5 1 2 5 1 3 3]
[ 9 11  8  5  7 11  8 11 12]
[-7 -7 -2  3  3  1  6  5  6]
[ 8 18 15  4 10 30  7 24 27]
[0.125      0.22222222 0.6        4.         2.5        1.2
 7.         2.66666667 3.        ]
[0 0 0 4 2 1 7 2 3]
[   1  512  243    4   25 7776    7  512  729]
[1 2 3 0 1 1 0 2 0]


In [155]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.random.randint(1,10,size=(3,3))
print(b2)
print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 // b2)
print(a2 ** b2)
print(a2 % b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 9 8]
 [8 9 4]
 [3 7 9]]
[[10 11 11]
 [12 14 10]
 [10 15 18]]
[[-8 -7 -5]
 [-4 -4  2]
 [ 4  1  0]]
[[ 9 18 24]
 [32 45 24]
 [21 56 81]]
[[0.11111111 0.22222222 0.375     ]
 [0.5        0.55555556 1.5       ]
 [2.33333333 1.14285714 1.        ]]
[[0 0 0]
 [0 0 1]
 [2 1 1]]
[[        1       512      6561]
 [    65536   1953125      1296]
 [      343   2097152 387420489]]
[[1 2 3]
 [4 5 2]
 [1 1 0]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [157]:
a1 = np.random.randint(-10,10,size=5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[-5 -4  4  9  2]
[5 4 4 9 2]
[5 4 4 9 2]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [159]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[-5 -4  4  9  2]
[25 16 16 81  4]
[       nan        nan 2.         3.         1.41421356]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


#### 지수와 로그 함수 (Exponential and Log Function)

In [161]:
a1 = np.random.randint(1,10,size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1,2))

[3 3 3 5 8]
[  20.08553692   20.08553692   20.08553692  148.4131591  2980.95798704]
[  8.   8.   8.  32. 256.]
[ 9  9  9 25 64]


In [162]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[3 3 3 5 8]
[1.09861229 1.09861229 1.09861229 1.60943791 2.07944154]
[1.5849625  1.5849625  1.5849625  2.32192809 3.        ]
[0.47712125 0.47712125 0.47712125 0.69897    0.90308999]


#### 삼각 함수(Trigonometrical Function)


In [163]:
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [164]:
x = [-1,0,1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

In [167]:
a2 = np.random.randint(1,10, size=(3,3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0), np.sum(a2,axis=0))
print(a2.sum(axis=1), np.sum(a2,axis=1))

[[3 8 4]
 [3 8 5]
 [2 7 5]]
45 45
[ 8 23 14] [ 8 23 14]
[15 16 14] [15 16 14]


#### cumsum(): 누적합 계산

In [168]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2,axis=0))
print(np.cumsum(a2,axis=1))

[[3 8 4]
 [3 8 5]
 [2 7 5]]
[ 3 11 15 18 26 31 33 40 45]
[[ 3  8  4]
 [ 6 16  9]
 [ 8 23 14]]
[[ 3 11 15]
 [ 3 11 16]
 [ 2  9 14]]


#### diff(): 차분 계산

In [169]:
print(a2)
print(np.diff(a2))
print(np.diff(a2,axis=0))
print(np.diff(a2,axis=1))

[[3 8 4]
 [3 8 5]
 [2 7 5]]
[[ 5 -4]
 [ 5 -3]
 [ 5 -2]]
[[ 0  0  1]
 [-1 -1  0]]
[[ 5 -4]
 [ 5 -3]
 [ 5 -2]]


#### prod(): 곱 계산

In [170]:
print(a2)
print(np.prod(a2))
print(np.prod(a2,axis=0))
print(np.prod(a2,axis=1))

[[3 8 4]
 [3 8 5]
 [2 7 5]]
806400
[ 18 448 100]
[ 96 120  70]


#### cumprod(): 누적곱 계산

In [171]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2,axis=0))
print(np.cumprod(a2,axis=1))

[[3 8 4]
 [3 8 5]
 [2 7 5]]
[     3     24     96    288   2304  11520  23040 161280 806400]
[[  3   8   4]
 [  9  64  20]
 [ 18 448 100]]
[[  3  24  96]
 [  3  24 120]
 [  2  14  70]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [172]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2,b2))
print(np.matmul(a2,b2))

[[3 8 4]
 [3 8 5]
 [2 7 5]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[15 15 15]
 [16 16 16]
 [14 14 14]]
[[15 15 15]
 [16 16 16]
 [14 14 14]]


#### tensordot(): 텐서곱 계산

In [175]:
print(a2)
print(b2)
print(np.tensordot(a2,b2))
print(np.tensordot(a2,b2,axes=0))
print(np.tensordot(a2,b2,axes=1))

[[3 8 4]
 [3 8 5]
 [2 7 5]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
45
[[[[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]]


 [[[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]]


 [[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]]]
[[15 15 15]
 [16 16 16]
 [14 14 14]]


#### cross(): 벡터곱

In [176]:
x = [1,2,3]
y = [4,5,6]
print(np.cross(x,y))

[-3  6 -3]


#### inner()/outer(): 내적/외적

In [177]:
print(a2)
print(b2)
print(np.inner(a2,b2))
print(np.outer(a2,b2))

[[3 8 4]
 [3 8 5]
 [2 7 5]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[15 15 15]
 [16 16 16]
 [14 14 14]]
[[3 3 3 3 3 3 3 3 3]
 [8 8 8 8 8 8 8 8 8]
 [4 4 4 4 4 4 4 4 4]
 [3 3 3 3 3 3 3 3 3]
 [8 8 8 8 8 8 8 8 8]
 [5 5 5 5 5 5 5 5 5]
 [2 2 2 2 2 2 2 2 2]
 [7 7 7 7 7 7 7 7 7]
 [5 5 5 5 5 5 5 5 5]]


#### mean(): 평균 계산

In [178]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis=0))
print(np.mean(a2, axis=1))

[[3 8 4]
 [3 8 5]
 [2 7 5]]
5.0
[2.66666667 7.66666667 4.66666667]
[5.         5.33333333 4.66666667]


#### std(): 표준 편차 계산

In [179]:
print(a2)
print(np.std(a2))
print(np.std(a2, axis=0))
print(np.std(a2, axis=1))

[[3 8 4]
 [3 8 5]
 [2 7 5]]
2.1081851067789197
[0.47140452 0.47140452 0.47140452]
[2.1602469  2.05480467 2.05480467]


#### var(): 분산 계산

In [180]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis=0))
print(np.var(a2, axis=1))

[[3 8 4]
 [3 8 5]
 [2 7 5]]
4.444444444444445
[0.22222222 0.22222222 0.22222222]
[4.66666667 4.22222222 4.22222222]


#### min(): 최소값

In [181]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[3 8 4]
 [3 8 5]
 [2 7 5]]
2
[2 7 4]
[3 3 2]


#### max(): 최대값

In [182]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis=0))
print(np.max(a2, axis=1))

[[3 8 4]
 [3 8 5]
 [2 7 5]]
8
[3 8 5]
[8 8 7]


#### argmin(): 최소값 인덱스

In [183]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2, axis=0))
print(np.argmin(a2, axis=1))

[[3 8 4]
 [3 8 5]
 [2 7 5]]
6
[2 2 0]
[0 0 0]


#### argmax(): 최대값 인덱스

In [184]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2, axis=0))
print(np.argmax(a2, axis=1))

[[3 8 4]
 [3 8 5]
 [2 7 5]]
1
[0 0 1]
[1 1 1]


#### median(): 중앙값

In [185]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis=0))
print(np.median(a2, axis=1))

[[3 8 4]
 [3 8 5]
 [2 7 5]]
5.0
[3. 8. 5.]
[4. 5. 5.]


#### percentile(): 백분위 수



In [190]:
a1 = np.array([0,1,2,3])
print(a1)
print(np.percentile(a1, [0,20,40,60,80,100],interpolation='linear'))
print(np.percentile(a1, [0,20,40,60,80,100],interpolation='higher'))
print(np.percentile(a1, [0,20,40,60,80,100],interpolation='lower'))
print(np.percentile(a1, [0,20,40,60,80,100],interpolation='nearest'))
print(np.percentile(a1, [0,20,40,60,80,100],interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


#### any()

In [193]:
a2 = np.array([[False, False,False],
              [False,True,True],
              [False, True, True]])
print(a2)
print(np.any(a2))
print(np.any(a2,axis=0))
print(np.any(a2,axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


#### all()

In [195]:
a2 = np.array([[False, False,True],
              [True,True,True],
              [False, True, True]])
print(a2)
print(np.all(a2))
print(np.all(a2,axis=0))
print(np.all(a2,axis=1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


### 비교 연산(Comparison Operators)


In [198]:
a1 = np.arange(1,10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1 <5)
print(a1 <= 5)
print(a1 > 5)
print(a1 <= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[ True  True  True  True  True False False False False]


In [204]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2 > 5))
print(np.sum(a2 > 5))
print(np.sum(a2 > 5, axis=0))
print(np.sum(a2 > 5, axis=1))
print(np.any(a2 > 5))
print(np.any(a2 > 5, axis=0))
print(np.any(a2 > 5, axis=1))
print(np.all(a2 > 5))
print(np.all(a2 > 5, axis=0))
print(np.all(a2 > 5, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
True
[ True  True  True]
[False  True  True]
False
[False False False]
[False False  True]


In [205]:
a1 = np.array([1,2,3,4,5])
print(a1)
b1 = np.array([1,2,3,3,4])
print(b1)
print(np.isclose(a1,b1))

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [209]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


#### 불리언 연산자(Boolean Operators)


In [214]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)

print((a2 > 5) & (a2 < 8))
print(a2[(a2 > 5) & (a2 < 8)])

print((a2 > 5) | (a2 < 8))
print(a2[(a2 > 5) | (a2 < 8)])

print((a2 > 5) ^ (a2 < 8))
print(a2[(a2 > 5) ^ (a2 < 8)])

print(~(a2 > 5))
print(a2[~(a2 > 5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


### 배열 정렬

In [218]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1))
print(a1)
print(a1.sort())
print(a1)

[9 7 9 9 5 6 8 9 4 5]
[4 5 5 6 7 8 9 9 9 9]
[9 7 9 9 5 6 8 9 4 5]
[8 4 9 5 1 6 0 2 3 7]
[9 7 9 9 5 6 8 9 4 5]
None
[4 5 5 6 7 8 9 9 9 9]


In [219]:
a2 = np.random.randint(1, 10 ,size=(3,3))
print(a2)
print(np.sort(a2,axis=0))
print(np.sort(a2,axis=1))

[[3 5 1]
 [9 2 8]
 [8 2 2]]
[[3 2 1]
 [8 2 2]
 [9 5 8]]
[[1 3 5]
 [2 8 9]
 [2 2 8]]


#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [220]:
a1 = np.random.randint(1,10,size=10)
print(a1)
print(np.partition(a1,3))

[1 3 5 8 6 2 8 1 1 3]
[1 1 1 2 3 3 8 8 5 6]


In [221]:
a2 = np.random.randint(1, 10, size = (5,5))
print(a2)
print(np.partition(a2,3))
print(np.partition(a2,3, axis=0))
print(np.partition(a2,3, axis=1))

[[7 7 3 9 5]
 [1 3 6 4 3]
 [2 7 5 1 6]
 [5 3 8 9 2]
 [2 9 9 3 7]]
[[3 5 7 7 9]
 [1 3 3 4 6]
 [1 2 5 6 7]
 [3 2 5 8 9]
 [3 2 7 9 9]]
[[1 3 3 1 2]
 [2 7 5 3 5]
 [2 3 6 4 3]
 [5 7 8 9 6]
 [7 9 9 9 7]]
[[3 5 7 7 9]
 [1 3 3 4 6]
 [1 2 5 6 7]
 [3 2 5 8 9]
 [3 2 7 9 9]]


## 배열 입출력


In [222]:
a2 = np.random.randint(1,10, size=(5,5))
print(a2)
np.save("a", a2)

[[7 6 4 2 8]
 [8 2 2 2 2]
 [9 8 5 1 4]
 [4 5 9 1 5]
 [1 2 2 9 2]]


In [223]:
!ls

a.npy  sample_data


In [224]:
b2 = np.random.randint(1,10,size=(5,5))
print(b2)
np.savez("ab", a2, b2)

[[5 2 1 7 1]
 [4 6 2 7 5]
 [2 7 3 7 5]
 [1 7 6 8 7]
 [8 3 8 6 2]]


In [225]:
!ls

ab.npz	a.npy  sample_data


In [226]:
npy = np.load("a.npy")
print(npy)

[[7 6 4 2 8]
 [8 2 2 2 2]
 [9 8 5 1 4]
 [4 5 9 1 5]
 [1 2 2 9 2]]


In [230]:
npz = np.load("ab.npz")
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[7 6 4 2 8]
 [8 2 2 2 2]
 [9 8 5 1 4]
 [4 5 9 1 5]
 [1 2 2 9 2]]
[[5 2 1 7 1]
 [4 6 2 7 5]
 [2 7 3 7 5]
 [1 7 6 8 7]
 [8 3 8 6 2]]


In [232]:
print(a2)
np.savetxt("a.csv", a2, delimiter=',')

[[7 6 4 2 8]
 [8 2 2 2 2]
 [9 8 5 1 4]
 [4 5 9 1 5]
 [1 2 2 9 2]]


In [233]:
!ls

ab.npz	a.csv  a.npy  sample_data


In [234]:
!cat a.csv

7.000000000000000000e+00,6.000000000000000000e+00,4.000000000000000000e+00,2.000000000000000000e+00,8.000000000000000000e+00
8.000000000000000000e+00,2.000000000000000000e+00,2.000000000000000000e+00,2.000000000000000000e+00,2.000000000000000000e+00
9.000000000000000000e+00,8.000000000000000000e+00,5.000000000000000000e+00,1.000000000000000000e+00,4.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,9.000000000000000000e+00,1.000000000000000000e+00,5.000000000000000000e+00
1.000000000000000000e+00,2.000000000000000000e+00,2.000000000000000000e+00,9.000000000000000000e+00,2.000000000000000000e+00


In [235]:
csv = np.loadtxt("a.csv", delimiter=',')
print(csv)

[[7. 6. 4. 2. 8.]
 [8. 2. 2. 2. 2.]
 [9. 8. 5. 1. 4.]
 [4. 5. 9. 1. 5.]
 [1. 2. 2. 9. 2.]]


In [236]:
print(b2)
np.savetxt("b.csv",b2,delimiter=',',fmt='%.2e',header='c1, c2, c3, c4, c5')

[[5 2 1 7 1]
 [4 6 2 7 5]
 [2 7 3 7 5]
 [1 7 6 8 7]
 [8 3 8 6 2]]


In [237]:
!cat b.csv

# c1, c2, c3, c4, c5
5.00e+00,2.00e+00,1.00e+00,7.00e+00,1.00e+00
4.00e+00,6.00e+00,2.00e+00,7.00e+00,5.00e+00
2.00e+00,7.00e+00,3.00e+00,7.00e+00,5.00e+00
1.00e+00,7.00e+00,6.00e+00,8.00e+00,7.00e+00
8.00e+00,3.00e+00,8.00e+00,6.00e+00,2.00e+00


In [238]:
csv = np.loadtxt("b.csv", delimiter=',')
print(csv)

[[5. 2. 1. 7. 1.]
 [4. 6. 2. 7. 5.]
 [2. 7. 3. 7. 5.]
 [1. 7. 6. 8. 7.]
 [8. 3. 8. 6. 2.]]




---

