# 텐서플로2 주요 특징

In [30]:
import tensorflow as tf
print(tf.executing_eagerly())

True


In [31]:
a = 1
b = 2
c = tf.math.add(a, b)
print(c)

tf.Tensor(3, shape=(), dtype=int32)


In [32]:
c.numpy()

3

# 텐서플로 자료구조

In [33]:
import tensorflow as tf

a = tf.constant(1)
b = tf.constant(2)
print("a:", a)
print("b:", b)

a: tf.Tensor(1, shape=(), dtype=int32)
b: tf.Tensor(2, shape=(), dtype=int32)


In [34]:
print(tf.rank(0))

tf.Tensor(0, shape=(), dtype=int32)


In [35]:
a = tf.cast(a, tf.float32)
b = tf.cast(b, tf.float32)
print(a.dtype)
print(b.dtype)

<dtype: 'float32'>
<dtype: 'float32'>


In [36]:
c = tf.math.add(a, b)
print("result:", c)
print("rank:", tf.rank(c))

result: tf.Tensor(3.0, shape=(), dtype=float32)
rank: tf.Tensor(0, shape=(), dtype=int32)


In [37]:
print(tf.math.subtract(a, b))

tf.Tensor(-1.0, shape=(), dtype=float32)


In [38]:
print(tf.math.multiply(a, b))

tf.Tensor(2.0, shape=(), dtype=float32)


In [39]:
print(tf.math.divide(a, b))

tf.Tensor(0.5, shape=(), dtype=float32)


In [40]:
print(tf.math.mod(a, b))

tf.Tensor(1.0, shape=(), dtype=float32)


In [41]:
print(tf.math.floordiv(a, b))

tf.Tensor(0.0, shape=(), dtype=float32)


In [42]:
import tensorflow as tf
import numpy as np

py_list = [10., 20., 30.]
num_arr = np.array([10., 10., 10.])

vec1 = tf.constant(py_list, dtype=tf.float32)
vec2 = tf.constant(num_arr, dtype=tf.float32)

print("vec1:", vec1)
print("vec2:", vec2)

vec1: tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
vec2: tf.Tensor([10. 10. 10.], shape=(3,), dtype=float32)


In [43]:
print(tf.rank(vec1)) 
print(tf.rank(vec2))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [44]:
add1 = tf.math.add(vec1, vec2)
print("result:", add1)
print("rank:", tf.rank(add1))

result: tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
rank: tf.Tensor(1, shape=(), dtype=int32)


In [45]:
add2 = vec1 + vec2
print("result:", add2)
print("rank:", tf.rank(add2))

result: tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
rank: tf.Tensor(1, shape=(), dtype=int32)


In [46]:
print(tf.math.subtract(vec1, vec2))
print(tf.math.multiply(vec1, vec2))
print(tf.math.divide(vec1, vec2))
print(tf.math.mod(vec1, vec2))
print(tf.math.floordiv(vec1, vec2))

tf.Tensor([ 0. 10. 20.], shape=(3,), dtype=float32)
tf.Tensor([100. 200. 300.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [47]:
print(vec1 - vec2)
print(vec1 * vec2)
print(vec1 / vec2)
print(vec1 % vec2)
print(vec1 // vec2)

tf.Tensor([ 0. 10. 20.], shape=(3,), dtype=float32)
tf.Tensor([100. 200. 300.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [48]:
print(tf.reduce_sum(vec1))
print(tf.reduce_sum(vec2))

tf.Tensor(60.0, shape=(), dtype=float32)
tf.Tensor(30.0, shape=(), dtype=float32)


In [49]:
print(tf.square(vec1))

tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)


In [50]:
print(vec1**2)

tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)


In [51]:
print(tf.sqrt(vec2))

tf.Tensor([3.1622777 3.1622777 3.1622777], shape=(3,), dtype=float32)


In [52]:
print(vec2**0.5)

tf.Tensor([3.1622777 3.1622777 3.1622777], shape=(3,), dtype=float32)


In [53]:
print(vec1 + 1)

tf.Tensor([11. 21. 31.], shape=(3,), dtype=float32)


In [54]:
import tensorflow as tf

list_of_list = [[10, 20], [30, 40]]

mat1 = tf.constant(list_of_list)

print("rank:", tf.rank(mat1))

print("mat1:", mat1)

rank: tf.Tensor(2, shape=(), dtype=int32)
mat1: tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


In [55]:
vec1 = tf.constant([1, 0])
vec2 = tf.constant([-1, 2])

mat2 = tf.stack([vec1, vec2])

print("rank:", tf.rank(mat2))

print("mat2:", mat2)

rank: tf.Tensor(2, shape=(), dtype=int32)
mat2: tf.Tensor(
[[ 1  0]
 [-1  2]], shape=(2, 2), dtype=int32)


In [56]:
element_mul = tf.math.multiply(mat1, mat2)
print("result:", element_mul)
print("rank:", tf.rank(element_mul))

result: tf.Tensor(
[[ 10   0]
 [-30  80]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [57]:
element_bc = tf.math.multiply(mat1, 3)
print("result:", element_bc)
print("rank:", tf.rank(element_bc))

result: tf.Tensor(
[[ 30  60]
 [ 90 120]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [58]:
mat_mul = tf.matmul(mat1, mat2)
print("result:", mat_mul)
print("rank:", tf.rank(mat_mul))

result: tf.Tensor(
[[-10  40]
 [-10  80]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [59]:
add1 = tf.math.add(mat1, mat2)
print("result:", add1)
print("rank:", tf.rank(add1))

result: tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [60]:
add2 = mat1 + mat2
print("result:", add2)
print("rank:", tf.rank(add2))

result: tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [61]:
np_arr = mat_mul.numpy()
print(type(np_arr))
print(np_arr)

<class 'numpy.ndarray'>
[[-10  40]
 [-10  80]]


In [62]:
import tensorflow as tf
import numpy as np

mat1 = [[1, 2, 3, 4],
        [5, 6, 7, 8]]

mat2 = [[9, 10, 11, 12],
        [13, 14, 15, 16]]

mat3 = [[17, 18, 19, 20],
        [21, 22, 23, 24]]

tensor1 = tf.constant([mat1, mat2, mat3])

print("rank:", tf.rank(tensor1))

print("tensor1:", tensor1)

rank: tf.Tensor(3, shape=(), dtype=int32)
tensor1: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [64]:
tensor2 = tf.stack([mat1, mat2, mat3])

print("rank:", tf.rank(tensor2))

print("tensor2:", tensor2)

rank: tf.Tensor(3, shape=(), dtype=int32)
tensor2: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [65]:
vec1 = [1, 2, 3, 4]
vec2 = [5, 6, 7, 8]
vec3 = [9, 10, 11, 12]
vec4 = [13, 14, 15, 16]
vec5 = [17, 18, 19, 20]
vec6 = [21, 22, 23, 24]

arr = [[vec1, vec2],
       [vec3, vec4],
       [vec5, vec6]]

tensor3 = tf.constant(arr)

print("rank:", tf.rank(tensor3))

print("tensor3:", tensor3)

rank: tf.Tensor(3, shape=(), dtype=int32)
tensor3: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [66]:
tensor4 = tf.stack([tensor1, tensor2])

print("rank:", tf.rank(tensor4))

print("tensor4:", tensor4)

rank: tf.Tensor(4, shape=(), dtype=int32)
tensor4: tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]], shape=(2, 3, 2, 4), dtype=int32)


# 인덱싱 (indexing)

In [67]:
import tensorflow as tf

vec = tf.constant([10, 20, 30, 40, 50])
print(vec)

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)


In [68]:
print(vec[0])

tf.Tensor(10, shape=(), dtype=int32)


In [69]:
print(vec[-1])

tf.Tensor(50, shape=(), dtype=int32)


In [70]:
print(vec[:3])

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [71]:
mat = tf.constant([[10, 20, 30],
                   [40, 50, 60]])

print(mat[0, 2])

tf.Tensor(30, shape=(), dtype=int32)


In [72]:
print(mat[0, :])

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [73]:
print(mat[:, 1])

tf.Tensor([20 50], shape=(2,), dtype=int32)


In [74]:
print(mat[:, :])

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [75]:
tensor = tf.constant([
  [[10, 20, 30],
   [40, 50, 60]],
   [[-10, -20, -30],
    [-40, -50, -60]]
])
print(tensor)

tf.Tensor(
[[[ 10  20  30]
  [ 40  50  60]]

 [[-10 -20 -30]
  [-40 -50 -60]]], shape=(2, 2, 3), dtype=int32)


In [77]:
print(tensor[0, :, :])

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [78]:
print(tensor[:, :2, :2])

tf.Tensor(
[[[ 10  20]
  [ 40  50]]

 [[-10 -20]
  [-40 -50]]], shape=(2, 2, 2), dtype=int32)


# 형태 변환(tf.reshape)

In [79]:
import tensorflow as tf

tensor = tf.constant(range(0, 24))
print(tensor)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)


In [80]:
tensor1 = tf.reshape(tensor, [3, 8])
print(tensor1)

tf.Tensor(
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]], shape=(3, 8), dtype=int32)


In [82]:
tensor2 = tf.reshape(tensor1, [-1, 4])
print(tensor2)

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]], shape=(6, 4), dtype=int32)


In [83]:
tensor3 = tf.reshape(tensor2, [-1])
print(tensor3)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)


In [84]:
tensor4 = tf.reshape(tensor3, [-1, 3, 4])
print(tensor4)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)


In [85]:
tensor5 = tf.reshape(tensor4, [3, 2, 4])
print(tensor5)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]], shape=(3, 2, 4), dtype=int32)


In [86]:
tensor6 = tf.reshape(tensor5, [3, 2, 2, 2])
print(tensor6)

tf.Tensor(
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]], shape=(3, 2, 2, 2), dtype=int32)


# 변수(tf.Variable)

In [87]:
import tensorflow as tf

tensor1 = tf.constant([[0, 1, 2],
                       [3, 4, 5]])
print(tensor1)

tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [88]:
tensor_var1 = tf.Variable(tensor1)
print(tensor_var1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]], dtype=int32)>


In [89]:
print("이름", tensor_var1.name)
print("크기", tensor_var1.shape)
print("자료형", tensor_var1.dtype)
print("배열", tensor_var1.numpy())

이름 Variable:0
크기 (2, 3)
자료형 <dtype: 'int32'>
배열 [[0 1 2]
 [3 4 5]]


In [91]:
tensor_var1.assign([[1, 1, 1],
                    [2, 2, 2]])
print(tensor_var1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]], dtype=int32)>


In [92]:
tensor2 = tf.convert_to_tensor(tensor_var1)
print(tensor2)

tf.Tensor(
[[1 1 1]
 [2 2 2]], shape=(2, 3), dtype=int32)


In [93]:
tensor_var2 = tf.Variable(tensor2, name='New Name')
print(tensor_var2.name)

New Name:0


In [94]:
tensor_var1 + tensor_var2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 2, 2],
       [4, 4, 4]], dtype=int32)>

# 자동 미분(Automatic Differentiation)

In [95]:
import tensorflow as tf

g = tf.random.Generator.from_seed(2020)
X = g.normal(shape=(10,))
Y = 3 * X - 2

print('X: ', X.numpy())
print('Y: ', Y.numpy())

X:  [-0.20943771  1.2746525   1.213214   -0.17576952  1.876984    0.16379918
  1.082245    0.6199966  -0.44402212  1.3048344 ]
Y:  [-2.628313    1.8239574   1.6396422  -2.5273085   3.630952   -1.5086024
  1.2467351  -0.14001012 -3.3320663   1.9145031 ]


In [96]:
def cal_mse(X, Y, a, b):

  Y_pred = a * X + b
  squared_error = (Y_pred - Y) ** 2
  mean_squared_error = tf.reduce_mean(squared_error)

  return mean_squared_error

In [97]:
a = tf.Variable(0.0)
b = tf.Variable(0.0)

EPOCHS = 200

for epoch in range(1, EPOCHS + 1):
  with tf.GradientTape() as tape:
    mse = cal_mse(X, Y, a, b)
  
  grad = tape.gradient(mse, {'a':a, 'b':b})
  d_a, d_b = grad['a'], grad['b']

  a.assign_sub(d_a * 0.05)
  b.assign_sub(d_b * 0.05)

  if epoch % 20 == 0:
    print("EPOCH %d - MSE: %.4f ---- a: %.2f ----b %.2f" %(epoch, mse, a, b))

EPOCH 20 - MSE: 1.1415 ---- a: 1.74 ----b -0.75
EPOCH 40 - MSE: 0.2881 ---- a: 2.37 ----b -1.37
EPOCH 60 - MSE: 0.0728 ---- a: 2.69 ----b -1.68
EPOCH 80 - MSE: 0.0184 ---- a: 2.84 ----b -1.84
EPOCH 100 - MSE: 0.0046 ---- a: 2.92 ----b -1.92
EPOCH 120 - MSE: 0.0012 ---- a: 2.96 ----b -1.96
EPOCH 140 - MSE: 0.0003 ---- a: 2.98 ----b -1.98
EPOCH 160 - MSE: 0.0001 ---- a: 2.99 ----b -1.99
EPOCH 180 - MSE: 0.0000 ---- a: 2.99 ----b -1.99
EPOCH 200 - MSE: 0.0000 ---- a: 3.00 ----b -2.00
